'use strict';

export const translations = {
  en: {
    subamountAnalyzer: "Subamount Analyzer",
    understandYourLoan: "Understand Your Loan & Save Money",
    loanDetails: "Loan Details",
    loanAmountLeft: "Loan Amount Left",
    interestRate: "Interest Rate",
    loanTime: "Loan Time",
    years: "years",
    extraPayment: "Extra Payment (Optional)",
    monthly: "Monthly",
    lumpSum: "Lump Sum (Yearly)",
    monthlyExtra: "Monthly Extra",
    lumpSumExtra: "Lump Sum Extra",
    optGoal: "Optimization Goal",
    reduceTime: "Reduce Loan Time",
    finishEarlier: "Finish loan earlier",
    reduceEmi: "Reduce EMI",
    lowerMonthly: "Lower monthly payment",
    analyzeBtn: "Analyze My Loan →",
    yourEmi: "Your Monthly EMI",
    loanSummary: "Loan Summary",
    totalPayable: "Total Payable",
    interestYouPay: "Interest You Pay",
    interestSaved: "Interest Saved",
    timeSaved: "Time Saved",
    viewDetails: "📅 View Detailed Breakdown",
    hideDetails: "📅 Hide Detailed Breakdown",
    yearlySchedule: "Yearly Loan Schedule",
    year: "Year",
    totalPaid: "Total Paid",
    interestPaid: "Interest Paid",
    principalPaid: "Principal Paid",
    remainingLoan: "Remaining Loan",
    footerNote: "Calculations are indicative. Consult your lender for exact figures.",
    loanAmountTooltip: "Total amount borrowed or left to pay",
    interestTooltip: "Annual interest rate charged by bank",
    timeTooltip: "Total number of years to repay",
    extraTooltip: "Additional payment you can make",
    // Summarizer translations
    aiLegalIntel: "AI Legal Intelligence",
    analyzeLoanBestWay: "Analyze Your Loan the Best Way",
    summarizerDesc: "Upload your agreement or paste the text and our AI will find hidden red flags, risky terms, and unfair charges.",
    processingEngine: "Processing Engine",
    pdfJsEngine: "PDF.js Engine",
    privacyFirst: "Privacy first processing",
    uploadDoc: "Upload Document (PDF)",
    analyzingPdf: "Analyzing PDF Content...",
    pdfLoaded: "PDF Loaded Successfully",
    clickToUpload: "Click to upload or drag & drop",
    readyForAnalysis: "Ready for Analysis",
    pdfOnly: "PDF Files only",
    agreementText: "Agreement Text",
    clearText: "Clear Text",
    pastePlaceholder: "Paste your legal text here (multiple pages supported)...",
    characters: "Characters",
    awaitingContent: "Awaiting Content",
    summarizing: "Summarizing Agreement...",
    analyzeNow: "Analyze Document Now →",
    analysisResult: "Analysis Result",
    generatedByAi: "Generated by Document AI Integration",
    legalWarning: "Warning: Legal AI summaries are indicative. Please consult a professional before signing any contract that involves red flags.",
    // Simulator and Loan Analyzer translations
    loanSimulator: "Loan Simulator",
    simulatorDesc: "Project prepayment impact and interest savings.",
    advFinProjection: "Advanced Financial Projection",
    effectiveTenure: "Effective Tenure",
    finishesInYear: "Finishes in Year",
    parameters: "Parameters",
    principal: "Principal",
    rate: "Rate",
    tenure: "Tenure",
    extraPrepay: "Extra Prepay",
    financialImpact: "Financial Impact",
    prepayImpact: (amount, interest, months) => `Prepaying ${amount} saves ${interest} in interest and closes loan ${months} months earlier.`,
    strategicNote: "Strategic Note",
    totalInterestNote: (total, percent) => `You will pay ${total} as total interest. This is ${percent}% of your principal.`,
    interestBurden: "Interest Burden",
    closingYear: "Closing Year",
    monthlyOutstanding: "Monthly Outstanding Balance",
    active: "Active",
    baseline: "Baseline",
    loanComposition: "Loan Composition",
    totalCost: "Total Cost",
    pVsI: "P vs I per Month",
    amortizationSchedule: "Amortization Schedule",
    detailedProjection: "Detailed month-by-month projection",
    prepayment: "Prepayment",
    balance: "Balance",
    simpleGuidance: "Simple money guidance for real loan decisions",
    loanDetailsBhar: "Loan details bharo, sliders adjust karo, aur Hinglish mein poochho: \"Agar main extra payment karu toh kya hoga?\"",
    estimatedEmi: "Estimated Monthly EMI",
    totalCostLoan: "Total Cost of Loan",
    paidTillNow: "Paid Till Now",
    advisorInsights: "Advisor Insights",
    bank: "Bank",
    type: "Type",
    monthsPaid: "Months Paid",
    monthsRemaining: "Months Remaining",
    repaymentTimeline: "Repayment Timeline",
    customEmi: "Custom EMI",
    basedOnCustom: "Based on your custom payment"
  },
  hi: {
    subamountAnalyzer: "सबअमाउंट एनालाइज़र",
    understandYourLoan: "अपना लोन समझें और पैसे बचाएं",
    loanDetails: "लोन विवरण",
    loanAmountLeft: "बची हुई लोन राशि",
    interestRate: "ब्याज दर",
    loanTime: "लोन का समय",
    years: "वर्ष",
    extraPayment: "अतिरिक्त भुगतान (वैकल्पिक)",
    monthly: "मासिक",
    lumpSum: "एकमुश्त (वार्षिक)",
    monthlyExtra: "मासिक अतिरिक्त",
    lumpSumExtra: "एकमुश्त अतिरिक्त",
    optGoal: "बचत का लक्ष्य",
    reduceTime: "लोन का समय कम करें",
    finishEarlier: "लोन जल्दी चुकाएं",
    reduceEmi: "EMI कम करें",
    lowerMonthly: "मासिक भुगतान कम करें",
    analyzeBtn: "मेरा लोन एनालाइज़ करें →",
    yourEmi: "आपकी मासिक EMI",
    loanSummary: "लोन सारांश",
    totalPayable: "कुल देय",
    interestYouPay: "आपका ब्याज",
    interestSaved: "बचाया गया ब्याज",
    timeSaved: "बचाया गया समय",
    viewDetails: "📅 विस्तृत ब्रेकडाउन देखें",
    hideDetails: "📅 विस्तृत ब्रेकडाउन छिपाएं",
    yearlySchedule: "वार्षिक लोन शिड्यूल",
    year: "वर्ष",
    totalPaid: "कुल भुगतान",
    interestPaid: "ब्याज का भुगतान",
    principalPaid: "मूलधन का भुगतान",
    remainingLoan: "शेष लोन",
    footerNote: "गणनाएँ सांकेतिक हैं। सटीक आँकड़ों के लिए अपने ऋणदाता से संपर्क करें।",
    loanAmountTooltip: "कुल उधार ली गई या शेष राशि",
    interestTooltip: "बैंक द्वारा लागू वार्षिक ब्याज दर",
    timeTooltip: "चुकाने के लिए वर्षों की कुल संख्या",
    extraTooltip: "अतिरिक्त भुगतान जो आप कर सकते हैं",
    // Summarizer translations
    aiLegalIntel: "AI कानूनी खुफिया",
    analyzeLoanBestWay: "अपने लोन का सही विश्लेषण करें",
    summarizerDesc: "अपना एग्रीमेंट अपलोड करें या टेक्स्ट पेस्ट करें और हमारा AI छिपे हुए जोखिमों और अनुचित शुल्कों का पता लगाएगा।",
    processingEngine: "प्रोसेसिंग इंजन",
    pdfJsEngine: "PDF.js इंजन",
    privacyFirst: "गोपनीयता पहले",
    uploadDoc: "दस्तावेज़ अपलोड करें (PDF)",
    analyzingPdf: "PDF सामग्री का विश्लेषण कर रहे हैं...",
    pdfLoaded: "PDF सफलतापूर्वक लोड हो गया",
    clickToUpload: "अपलोड करने के लिए क्लिक करें या ड्रैग एंड ड्रॉप करें",
    readyForAnalysis: "विश्लेषण के लिए तैयार",
    pdfOnly: "केवल PDF फ़ाइलें",
    agreementText: "एग्रीमेंट टेक्स्ट",
    clearText: "टेक्स्ट साफ करें",
    pastePlaceholder: "अपना कानूनी टेक्स्ट यहाँ पेस्ट करें...",
    characters: "अक्षर",
    awaitingContent: "सामग्री की प्रतीक्षा है",
    summarizing: "एग्रीमेंट का सारांश बना रहे हैं...",
    analyzeNow: "अभी विश्लेषण करें →",
    analysisResult: "विश्लेषण का परिणाम",
    generatedByAi: "दस्तावेज़ AI द्वारा जनरेट किया गया",
    legalWarning: "चेतावनी: कानूनी AI सारांश सांकेतिक हैं। किसी भी अनुबंध पर हस्ताक्षर करने से पहले पेशेवर से सलाह लें।",
    // Simulator and Loan Analyzer translations
    loanSimulator: "लोन सिम्युलेटर",
    simulatorDesc: "प्री-पेमेंट के प्रभाव और ब्याज की बचत का अनुमान लगाएं।",
    advFinProjection: "उन्नत वित्तीय प्रोजेक्शन",
    effectiveTenure: "प्रभावी अवधि",
    finishesInYear: "वर्ष में समाप्त होगा",
    parameters: "पैरामीटर्स",
    principal: "मूलधन",
    rate: "दर",
    tenure: "अवधि",
    extraPrepay: "अतिरिक्त प्री-पेमेंट",
    financialImpact: "वित्तीय प्रभाव",
    prepayImpact: (amount, interest, months) => `${amount} का प्री-पेमेंट करने से ${interest} ब्याज की बचत होगी और लोन ${months} महीने पहले खत्म होगा।`,
    strategicNote: "रणनीतिक नोट",
    totalInterestNote: (total, percent) => `आप कुल ${total} ब्याज के रूप में भुगतान करेंगे। यह आपके मूलधन का ${percent}% है।`,
    interestBurden: "ब्याज का बोझ",
    closingYear: "समाप्ति वर्ष",
    monthlyOutstanding: "मासिक शेष राशि",
    active: "सक्रिय",
    baseline: "बेसलाइन",
    loanComposition: "लोन की संरचना",
    totalCost: "कुल लागत",
    pVsI: "मूलधन बनाम ब्याज (प्रति माह)",
    amortizationSchedule: "अमोर्टाइजेशन शेड्यूल",
    detailedProjection: "विस्तृत महीने-दर-महीने प्रोजेक्शन",
    prepayment: "प्री-पेमेंट",
    balance: "शेष राशि",
    simpleGuidance: "असली लोन फैसलों के लिए आसान पैसे की सलाह",
    loanDetailsBhar: "लोन विवरण भरें, स्लाइडर्स एडजस्ट करें, और पूछें: \"अगर मैं एक्स्ट्रा पेमेंट करूँ तो क्या होगा?\"",
    estimatedEmi: "अनुमानित मासिक EMI",
    totalCostLoan: "लोन की कुल लागत",
    paidTillNow: "अब तक भुगतान किया गया",
    advisorInsights: "सलाहकार की अंतर्दृष्टि",
    bank: "बैंक",
    type: "प्रकार",
    monthsPaid: "कितने महीने भरे",
    monthsRemaining: "कितने महीने बचे",
    repaymentTimeline: "पुनर्भुगतान समयरेखा",
    customEmi: "कस्टम EMI",
    basedOnCustom: "आपके कस्टम भुगतान के आधार पर"
  },
  hinglish: {
    subamountAnalyzer: "Subamount Analyzer",
    understandYourLoan: "Apna Loan Samjho aur Paise Bachao",
    loanDetails: "Loan Details",
    loanAmountLeft: "Bacha Hua Loan Amount",
    interestRate: "Interest Rate",
    loanTime: "Loan Ka Time",
    years: "saal",
    extraPayment: "Extra Payment (Optional)",
    monthly: "Monthly",
    lumpSum: "Ek Saath (Yearly)",
    monthlyExtra: "Monthly Extra",
    lumpSumExtra: "Lump Sum Extra",
    optGoal: "Bachat Ka Goal",
    reduceTime: "Loan Time Kam Karein",
    finishEarlier: "Loan jaldi khatm karein",
    reduceEmi: "EMI Kam Karein",
    lowerMonthly: "Monthly payment kam karein",
    analyzeBtn: "Mera Loan Analyze Karein →",
    yourEmi: "Aapki Monthly EMI",
    loanSummary: "Loan Summary",
    totalPayable: "Total Dena Hoga",
    interestYouPay: "Aapka Interest",
    interestSaved: "Interest Bachat",
    timeSaved: "Time Bachat",
    viewDetails: "📅 Poori Details Dekhein",
    hideDetails: "📅 Details Chupayein",
    yearlySchedule: "Yearly Loan Schedule",
    year: "Saal",
    totalPaid: "Total Diya",
    interestPaid: "Interest Diya",
    principalPaid: "Principal Diya",
    remainingLoan: "Bacha Hua Loan",
    footerNote: "Calculations sirf idea dene ke liye hain. Details ke liye bank se baat karein.",
    loanAmountTooltip: "Total loan amount jo bacha hai",
    interestTooltip: "Bank ka saalana interest rate",
    timeTooltip: "Loan chukane ke liye total saal",
    extraTooltip: "Koi extra paisa jo aap de sakte hain",
    // Summarizer translations
    aiLegalIntel: "AI Legal Intelligence",
    analyzeLoanBestWay: "Apne Loan Ko Sahi Se Analyze Karein",
    summarizerDesc: "Apna agreement upload karein ya text paste karein, hamara AI hidden red flags aur galat charges dhoond lega.",
    processingEngine: "Processing Engine",
    pdfJsEngine: "PDF.js Engine",
    privacyFirst: "Privacy ka pura dhyan",
    uploadDoc: "Document Upload Karein (PDF)",
    analyzingPdf: "PDF Content analyze ho raha hai...",
    pdfLoaded: "PDF Sahi Se Load Ho Gaya",
    clickToUpload: "Upload karne ke liye click karein ya drag-drop karein",
    readyForAnalysis: "Analysis Ke Liye Taiyar",
    pdfOnly: "Sirf PDF Files",
    agreementText: "Agreement Text",
    clearText: "Text Saaf Karein",
    pastePlaceholder: "Apna legal text yahan paste karein...",
    characters: "Characters",
    awaitingContent: "Content Ka Intezar Hai",
    summarizing: "Agreement Summarize Ho Raha Hai...",
    analyzeNow: "Abhi Analyze Karein →",
    analysisResult: "Analysis Result",
    generatedByAi: "Document AI se banaya gaya",
    legalWarning: "Warning: AI summaries sirf idea ke liye hain. Sign karne se pehle expert se baat karein.",
    // Simulator and Loan Analyzer translations
    loanSimulator: "Loan Simulator",
    simulatorDesc: "Project prepayment impact and interest savings.",
    advFinProjection: "Advanced Financial Projection",
    effectiveTenure: "Effective Tenure",
    finishesInYear: "Closing Year",
    parameters: "Parameters",
    principal: "Principal",
    rate: "Rate",
    tenure: "Tenure",
    extraPrepay: "Extra Prepay",
    financialImpact: "Financial Impact",
    prepayImpact: (amount, interest, months) => `${amount} prepay karne se ${interest} interest bachega aur loan ${months} months pehle khatam hoga.`,
    strategicNote: "Strategic Note",
    totalInterestNote: (total, percent) => `Aap total ${total} interest bharenge. Ye aapke principal ka ${percent}% hai.`,
    interestBurden: "Interest Burden",
    closingYear: "Closing Year",
    monthlyOutstanding: "Monthly Outstanding Balance",
    active: "Active",
    baseline: "Baseline",
    loanComposition: "Loan Composition",
    totalCost: "Total Cost",
    pVsI: "P vs I per Month",
    detailedProjection: "Poori detail month-by-month",
    prepayment: "Prepayment",
    balance: "Balance",
    simpleGuidance: "Loan decisions ke liye simple guidance",
    loanDetailsBhar: "Loan details bharo, sliders adjust karo, aur Hinglish mein poochho: \"Agar main extra payment karu toh kya hoga?\"",
    estimatedEmi: "Estimated Monthly EMI",
    totalCostLoan: "Loan ki Total Cost",
    paidTillNow: "Ab tak diya",
    advisorInsights: "Advisor Insights",
    bank: "Bank",
    type: "Type",
    monthsPaid: "Kitne months bhare",
    monthsRemaining: "Kitne months bache",
    repaymentTimeline: "Repayment Timeline",
    customEmi: "Custom EMI",
    basedOnCustom: "Aapke custom payment ke basis par"
  }
};

export function fmtINR(n) {
  if (isNaN(n) || n == null) return '—';
  n = Math.round(n);
  if (n >= 10000000) return '₹' + (n / 10000000).toFixed(2) + ' Cr';
  if (n >= 100000)   return '₹' + (n / 100000).toFixed(2) + ' L';
  return '₹' + n.toLocaleString('en-IN');
}

export function fmtMonths(m, lang = 'en') {
  if (!m || m <= 0) return '—';
  const ys = lang === 'hi' ? 'वर्ष' : lang === 'hinglish' ? 'saal' : 'yr';
  const ysPlural = lang === 'hi' ? 'वर्ष' : lang === 'hinglish' ? 'saal' : 'yrs';
  const moStr = lang === 'hi' ? 'माह' : lang === 'hinglish' ? 'mahina' : 'mo';
  
  const y = Math.floor(m / 12), mo = m % 12;
  return (y ? y + ' ' + (y > 1 ? ysPlural : ys) + ' ' : '') + (mo ? mo + ' ' + moStr : '');
}

export function calcEMI(P, r, n) {
  if (r === 0) return P / n;
  return P * r * Math.pow(1 + r, n) / (Math.pow(1 + r, n) - 1);
}

export function amortize(P, annualRate, tenureMonths, globalExtra, xType, mode) {
  const r   = annualRate / 100 / 12;
  const emi = calcEMI(P, r, tenureMonths);
  let   bal = P;
  const rows = [];

  if (xType === 'lump' && globalExtra > 0) bal = Math.max(0, bal - globalExtra);

  let dynEMI = emi;

  for (let m = 1; m <= tenureMonths * 2; m++) {
    if (bal <= 0) break;

    const intPart = bal * r;
    let   prinPart = dynEMI - intPart;
    if (prinPart <= 0) prinPart = 0.01;

    let sub = 0;

    if (xType === 'monthly' && globalExtra > 0) {
      if (mode === 'tenure') {
        sub      += globalExtra;
        prinPart += globalExtra;
      } else {
        sub      += globalExtra;
        prinPart += globalExtra;
        const remM = tenureMonths - m;
        if (remM > 0) {
          const nb = Math.max(0, bal - prinPart);
          dynEMI   = calcEMI(nb, r, remM);
        }
      }
    }

    bal = Math.max(0, bal - prinPart);
    rows.push({
      month:     m,
      interest:  intPart,
      principal: prinPart - sub,
      sub:       sub,
      balance:   bal,
      emi:       dynEMI
    });
    if (bal <= 0) break;
  }

  return { rows, baseEMI: emi };
}

export function yearBuckets(rows) {
  const b = {};
  rows.forEach(r => {
    const yr = Math.ceil(r.month / 12);
    if (!b[yr]) b[yr] = { year: yr, principal: 0, interest: 0, sub: 0, balance: r.balance };
    b[yr].principal += r.principal;
    b[yr].interest  += r.interest;
    b[yr].sub       += r.sub;
    b[yr].balance    = r.balance;
  });
  return Object.values(b);
}
